<?php
/** @var $matricola
 *  @var $basepath
 */
?>
<?php $this->layout('home', [
        'title' => 'Inserisci voto',
])
?>
<h1>Inserisci voto</h1>
<p>Studente matricola: <?=$matricola?></p>
<form class="form-horizontal" action="<?=$basepath?>/studente/<?=$matricola?>/voto" method="post">
    <div class="input-group">
        <span class="input-group-addon col-4">Voto</span>
        <input type="text" class="form-input" placeholder="Voto, per i decimali usa il punto" name="voto">
        <input type="submit" class="btn btn-primary" value="Inserisci">
    </div>
</form>