<?php
/** @var $name */
/** @var $basepath */
?>
<?php $this->layout('home', [
        'title' => 'Inserisci studente',
])
?>
<h1>Inserisci studente</h1>
<form class="form-horizontal" action="<?=$basepath?>/studente" method="post">

    <div class="form-group col-12">
        <div class="col-12">
            <div class="input-group">
                <span class="input-group-addon col-3">Matricola</span>
                <input type="text" class="form-input" name="matricola">
            </div>
        </div>
    </div>
    <div class="form-group col-12">
        <div class="col-12">

        <div class="input-group">
            <span class="input-group-addon col-3">Cognome</span>
            <input type="text" class="form-input" name="cognome">
        </div>
        </div>
    </div>
    <div class="form-group col-12">
        <div class="col-12">

        <div class="input-group">
            <span class="input-group-addon col-3">Nome</span>
            <input type="text" class="form-input" name="nome">
        </div>
        </div>
    </div>
    <div class="form-group col-12">
        <div class="col-12">

            <input type="submit" value="Inserisci studente">

        </div>
    </div>
</form>